server:
  port: 8086

spring:
  profiles:
    active: test
  application:
    name: userService

  datasource:
    url: jdbc:mysql://192.168.0.143:3306/jt_test
    username: t_user1
    password: 123456
    #url: jdbc:mysql://192.168.0.205:3306/jt_test?characterEncoding=UTF-8&useSSL=true
    #username: jt_test
    #password: jt123456
    #url: jdbc:mysql://192.168.0.206:3306/op_test_lj?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    #username: root
    #password: Jt123$%^
    initialize: true
    driver-class-name: com.mysql.jdbc.Driver
    #driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show_sql: false
    format_sql: true
    database: MYSQL
    generate-ddl: true
    open-in-view: true
    hibernate:
      hbm2ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  #zipkin:
  #  base-url: http://localhost:8087
  data:
    mongodb:
      uri: mongodb://t_user1:123456@192.168.0.142:2017/jt_test

  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

  session:
    timeout: 1200000

  #spring-boot整合单机版redis redis作为缓存
  redis:
    hostName: 192.168.0.142
    port: 6379
    password: 123456
    database: 0 #默认使用db0
    timeout: 0
    topicName: chat
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0

  activemq:
    broker-url: tcp://192.168.0.142:61616
    in-memory: true
    password: admin
    user: admin
    packages:
      trust-all: false
    pool:
      enabled: false
      expiry-timeout: 0
      idle-timeout: 30000
      max-connections: 1

logging:
  pattern:
    console: "%d - %msg%n"
  level:
    com.mongcent.tnaot: debug
    org.springfromework: info
    org.hibernate: error
  file: log/user-service.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

